version: '3.8'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: f1_database
    ports:
      - '3307:3306'

  f1app:
    container_name: f1
    image: webf1-1
    build: .
    ports:
      - '8080:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/f1_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    depends_on:
      - mysql