spring:
  profiles :
    active : dev
  datasource:
    url : jdbc:mysql://localhost:3306/f1_database
    username : f1_database@localhost
    password : 12345678
  jpa :
    hibernate :
      ddl-auto : update
  thymeleaf:
    suffix : .html
  sql :
    init :
      mode : always
  liquibase :
    change-log : classpath:/db/changelog/db.changelog-master.yaml
  security:
    user :
      password : password
